# ข้อมูลบัญชี GitHub ของคุณ
owner: kawinprogrammer04
repo: my-status-page

# รายชื่อเว็บไซต์ที่คุณต้องการมอนิเตอร์ (ตรวจสอบจาก Plesk)
sites:
  - name: Kawin Brothers
    url: https://crm.kawinbrothers.com
  - name: Kawin Fulfillment
    url: https://ffm.kawinbrothers.com

status-website:
  # หากคุณยังไม่ได้ตั้งค่า Domain ตัวเอง ให้เอาเครื่องหมาย # หน้า baseUrl ออก
  # และใส่ชื่อ repo ของคุณ เพื่อให้เข้าผ่าน https://kawinprogrammer04.github.io/my-status-page
  baseUrl: /my-status-page
  
  # ถ้าในอนาคตจะใช้ status.yourdomain.com ให้ใส่ที่ cname และใส่ # หน้า baseUrl แทน
  # cname: status.kawinfulfillment.com

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kawin Status Page
  introTitle: "**Kawin Systems** Operational Status"
  introMessage: หน้าแสดงสถานะการทำงานของระบบในเครือ Kawin Group ทั้งหมด ระบบนี้ทำงานแยกส่วนกับเซิร์ฟเวอร์หลักเพื่อให้คุณมั่นใจได้ว่าข้อมูลสถานะจะออนไลน์เสมอ
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kawinprogrammer04/my-status-page

# ตั้งค่าการแจ้งเตือนเพิ่มเติมได้ที่นี่
