name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  repository_dispatch:
    types: [static_site]
  workflow_dispatch:
  push:
    paths:
      - ".upptimerc.yml"

# เพิ่มสิทธิ์ให้ GitHub Actions สามารถ Deploy ไปยัง Pages ได้
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    name: Build and deploy site
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Generate site
        uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      # ขั้นตอนการเตรียมไฟล์สำหรับ GitHub Actions Deploy
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # ชี้ไปยังโฟลเดอร์ที่ Upptime สร้างไฟล์หน้าเว็บไว้
          path: "site/status-page/__sapper__/export/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
